// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")public final class BackwardResult extends Table {
  public static BackwardResult getRootAsBackwardResult(ByteBuffer _bb) { return getRootAsBackwardResult(_bb, new BackwardResult()); }
  public static BackwardResult getRootAsBackwardResult(ByteBuffer _bb, BackwardResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BackwardResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Tensor gradInput() { return gradInput(new Tensor()); }
  public Tensor gradInput(Tensor obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createBackwardResult(FlatBufferBuilder builder,
      int grad_inputOffset) {
    builder.startObject(1);
    BackwardResult.addGradInput(builder, grad_inputOffset);
    return BackwardResult.endBackwardResult(builder);
  }

  public static void startBackwardResult(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addGradInput(FlatBufferBuilder builder, int gradInputOffset) { builder.addOffset(0, gradInputOffset, 0); }
  public static int endBackwardResult(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

