// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")public final class BatchOperationResult extends Table {
  public static BatchOperationResult getRootAsBatchOperationResult(ByteBuffer _bb) { return getRootAsBatchOperationResult(_bb, new BatchOperationResult()); }
  public static BatchOperationResult getRootAsBatchOperationResult(ByteBuffer _bb, BatchOperationResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BatchOperationResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Message results(int j) { return results(new Message(), j); }
  public Message results(Message obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int resultsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createBatchOperationResult(FlatBufferBuilder builder,
      int resultsOffset) {
    builder.startObject(1);
    BatchOperationResult.addResults(builder, resultsOffset);
    return BatchOperationResult.endBatchOperationResult(builder);
  }

  public static void startBatchOperationResult(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addResults(FlatBufferBuilder builder, int resultsOffset) { builder.addOffset(0, resultsOffset, 0); }
  public static int createResultsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startResultsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBatchOperationResult(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

