// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")public final class BatchOperation extends Table {
  public static BatchOperation getRootAsBatchOperation(ByteBuffer _bb) { return getRootAsBatchOperation(_bb, new BatchOperation()); }
  public static BatchOperation getRootAsBatchOperation(ByteBuffer _bb, BatchOperation obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BatchOperation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Message operations(int j) { return operations(new Message(), j); }
  public Message operations(Message obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int operationsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createBatchOperation(FlatBufferBuilder builder,
      int operationsOffset) {
    builder.startObject(1);
    BatchOperation.addOperations(builder, operationsOffset);
    return BatchOperation.endBatchOperation(builder);
  }

  public static void startBatchOperation(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addOperations(FlatBufferBuilder builder, int operationsOffset) { builder.addOffset(0, operationsOffset, 0); }
  public static int createOperationsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startOperationsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endBatchOperation(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

