// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")public final class Forward extends Table {
  public static Forward getRootAsForward(ByteBuffer _bb) { return getRootAsForward(_bb, new Forward()); }
  public static Forward getRootAsForward(ByteBuffer _bb, Forward obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Forward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public Tensor input() { return input(new Tensor()); }
  public Tensor input(Tensor obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createForward(FlatBufferBuilder builder,
      int nameOffset,
      int inputOffset) {
    builder.startObject(2);
    Forward.addInput(builder, inputOffset);
    Forward.addName(builder, nameOffset);
    return Forward.endForward(builder);
  }

  public static void startForward(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addInput(FlatBufferBuilder builder, int inputOffset) { builder.addOffset(1, inputOffset, 0); }
  public static int endForward(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

