// automatically generated by the FlatBuffers compiler, do not modify

package ppx;

public final class MessageBody {
  private MessageBody() { }
  public static final byte NONE = 0;
  public static final byte Handshake = 1;
  public static final byte HandshakeResult = 2;
  public static final byte Run = 3;
  public static final byte RunResult = 4;
  public static final byte Sample = 5;
  public static final byte SampleResult = 6;
  public static final byte Observe = 7;
  public static final byte ObserveResult = 8;
  public static final byte Tag = 9;
  public static final byte TagResult = 10;
  public static final byte Forward = 11;
  public static final byte ForwardResult = 12;
  public static final byte Backward = 13;
  public static final byte BackwardResult = 14;
  public static final byte Reset = 15;

  public static final String[] names = { "NONE", "Handshake", "HandshakeResult", "Run", "RunResult", "Sample", "SampleResult", "Observe", "ObserveResult", "Tag", "TagResult", "Forward", "ForwardResult", "Backward", "BackwardResult", "Reset", };

  public static String name(int e) { return names[e]; }
}

